### ISSUE TITLE
k8s secret content

### ISSUE THREAD

**Issue by mikearruda** [sqmgr/sqmgr-api#16]
Hi, I am using the k8s manifests to deploy, but it's failing on missing `sqmgr-config` and `sqmgr-jwt-keys` secrets. What should be used as content for these secrets?

**Comment by weters** [comment]
@mikearruda you can run `make .keys/public.pem` to generate the keys. I have a `sqmgr-config` set up like so:

```
apiVersion: v1
stringData:
  PG_DBNAME: <removed>
  PG_HOST: <removed>
  PG_PASSWORD: <removed>
  PG_PORT: <removed>
  PG_SSLMODE: <removed>
  PG_USER: <removed>
kind: Secret
```

You'll also want to create another secret called `sqmgr-jwt-keys` with the results from the make command

```
apiVersion: v1
data:
  private.pem: <removed>
  public.pem: <removed>
kind: Secret
```
